version: '3'
services:
  nginx:
    build: ./nginx
    image: nginx:my
    container_name: nginx
    volumes:
      - "./data/vhosts.d:/etc/nginx/vhosts.d"           
      - "./data/certs:/etc/nginx/ssl"                     
      - "./data/www/acme:/var/www/acme"                           
      - "/var/log/nginx:/var/log/nginx"
    ports:                                              
      - "80:80"                                         
      - "443:443"                                       
    restart: always                                     
    depends_on:
      - gitsrv

  acme:
    build: ./acme
    image: acme:my
    container_name: acme
    volumes:
      - "./data/certs:/acme/certs"
      - "./data/www/acme:/acme/www"
      - "/var/log/acme:/var/log/acme"
    restart: always
    depends_on:
      - nginx

  gitsrv:
    build: ./gitsrv
    image: gitsrv:my
    container_name: gitsrv
    volumes:
      - "/var/www/code:/var/repo"
    restart: always
